const userConstants = {
    USER_GET_SUCCESS : "USER_GET_SUCCESS",
    USER_GET_FAIL: "USER_GET_FAIL",
    USER_DEL_FAIL: " USER_DEL_FAIL",
    USER_DEL_SUCCES: "USER_DEL_SUCCES",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
    USER_LOGOUT: "USER_LOGOUT",
    USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST"

}
export default userConstants
