const userConstants = {
    ROOM_GET_SUCCESS : "ROOM_GET_SUCCESS",
    ROOM_GET_FAIL : "ROOM_GET_FAIL",
    USER_GET_SUCCESS : "USER_GET_SUCCESS",
    USER_GET_FAIL: "USER_GET_FAIL",
    USER_DEL_FAIL: " USER_DEL_FAIL",
    USER_DEL_SUCCES: "USER_DEL_SUCCES",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
    USER_LOGOUT: "USER_LOGOUT",
    USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
    APPROVE_ROOM_SUCCESS: "APPROVE_ROOM_SUCCESS",
    APPROVE_ROOM_FAIL: "APPROVE_ROOM_FAIL",
    REQUEST_GET_SUCCESS : "REQUEST_GET_SUCCESS",
    REQUEST_GET_FAIL : "REQUEST_GET_FAIL",
    APPROVE_REQUEST_SUCCESS : " APPROVE_REQUEST_SUCCESS",
    APPROVE_REQUEST_FAIL : "APPROVE_REQUEST_FAIL"



}
export default userConstants
